# Generated by Django 3.1 on 2020-10-31 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_auto_20201031_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
