# Generated by Django 3.1 on 2020-10-31 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_auto_20201031_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='post',
        ),
    ]
