# Generated by Django 3.1.2 on 2020-11-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0010_aboutsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_views',
            field=models.ImageField(blank=True, default=0, null=True, upload_to=''),
        ),
    ]
