# Generated by Django 3.1.2 on 2020-11-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0013_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Profile/<django.db.models.fields.CharField>')),
                ('facebook', models.URLField()),
                ('whatsapp', models.URLField()),
                ('insta', models.URLField()),
                ('twitter', models.URLField()),
                ('github', models.URLField()),
                ('linkedln', models.URLField()),
            ],
        ),
    ]
