# Generated by Django 3.1.2 on 2020-11-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0014_profilecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecard',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profilecard',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profilecard',
            name='insta',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profilecard',
            name='linkedln',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profilecard',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profilecard',
            name='whatsapp',
            field=models.URLField(blank=True),
        ),
    ]
